### ISSUE TITLE
Cant't enable Shazam (1.3.12) in REDCap 13.3.4

### ISSUE THREAD

**Issue by ChrWelker** [susom/redcap-em-shazam#51]
[Shazam_error.pdf](https://github.com/susom/redcap-em-shazam/files/11089757/Shazam_error.pdf)

and 
https://redcap.vanderbilt.edu/community/post.php?id=200740&comment=201835

Is the reason php 7.3.31?

**Comment by 123andy** [comment]
Can you please provide more detail, @ChrWelker -- you were trying to enable 1.3.12 with php 7.3 and it threw an error?   I think PHP 7.3 is no longer supported but I can't see what version of REDCap you are running.

**Comment by ChrWelker** [comment]
The REDCap version is indicated in the title and in the error message in the PDF file I provided: It is REDCap 13.3.4.
In the REDCap control panel it says that this version is still compatible with php 7.3.31, so my question is if Shazam might not be compatible.

**Comment by 123andy** [comment]
Hi @ChrWelker - I just set up REDCap:
```
Server info: REDCap 13.3.4 · PHP 8.1.16 (Linux/Unix OS) · MySQL 8.0.31
```
and was able to enable both Shazam versions 1.13.12 and 1.13.13 repeatedly.

I then rebuilt my system to 7.3-apache-buster and tried again.
I can confirm an error when trying to enable v1.13.12.  However, it works fine with the newer version 1.13.13.

The issue is apparently that 1.13.12 contains:
```
    private bool $config_loaded = false;
```
where specifying the type of the variable is not supported in php 7.3.

For what it is worth, it is recommended you upgrade to php 7.4 or greater.

![image](https://user-images.githubusercontent.com/7461553/229559020-1b860133-4539-466e-b214-b27709674085.png)

**Comment by 123andy** [comment]
So, you can either remove the 'bool' word on line 11 of Shazam.php and it should work, or you can upgrade to 1.13.13 but perhaps there is a chance that this version isn't supported on your platform.  The other choice, I guess, is to go back to the version before 1.13.12 and see if that works for you.

**Comment by ChrWelker** [comment]
Than you so much. We will update php as soon as possible. Until then, I went back to Shazam 1.13.10 and it seems to work without problems.
